//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int id { get; set; }
        public int emisorId { get; set; }
        public int receptorId { get; set; }
        public string mensaje { get; set; }
        public System.DateTime fechaEnvio { get; set; }
        public int productoId { get; set; }
        public string respuesta { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
