//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoProducto
    {
        public int productoId { get; set; }
        public int pedidoId { get; set; }
        public int cantidad { get; set; }
        public int estadoPedidoId { get; set; }
        public double subtotal { get; set; }
    
        public virtual EstadoPedido EstadoPedido { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}
